"""sync cache (N7)

`org_map` and `agreement_cache` are **node-global** (R10): an agreement is between two
organisations, so it belongs to neither tenant's rows, and filtering it by tenant would
return nothing and quietly deny every cross-org read.

Both are caches, not records. The Cloud owns them; a pull replaces each set wholesale,
because a revocation is an absence from the feed and a merge would never notice one.

There is no table for sync liveness. It is held in memory, so a restart reports the age
of the process rather than the age of the cache — see `sync.SyncState`.

Revision ID: 15e0f9bece1b
Revises: 3778de9637e2
Create Date: 2026-09-29 18:55:02.119500

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel renders its own column types (AutoString), so autogenerated
# migrations reference it by name and need it imported.
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15e0f9bece1b"
down_revision: str | Sequence[str] | None = "3778de9637e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agreement_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_org", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("consumer_org", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("actions", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("valid_from", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("valid_until", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=True),
        sa.Column("synced_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agreement_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agreement_cache_consumer_org"), ["consumer_org"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agreement_cache_provider_org"), ["provider_org"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agreement_cache_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agreement_cache_status"), ["status"], unique=False)

    op.create_table(
        "org_map",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("group_path", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("synced_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    with op.batch_alter_table("org_map", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_org_map_group_path"), ["group_path"], unique=False)
        batch_op.create_index(batch_op.f("ix_org_map_org_id"), ["org_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("org_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_org_map_org_id"))
        batch_op.drop_index(batch_op.f("ix_org_map_group_path"))

    op.drop_table("org_map")
    with op.batch_alter_table("agreement_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agreement_cache_status"))
        batch_op.drop_index(batch_op.f("ix_agreement_cache_resource_id"))
        batch_op.drop_index(batch_op.f("ix_agreement_cache_provider_org"))
        batch_op.drop_index(batch_op.f("ix_agreement_cache_consumer_org"))

    op.drop_table("agreement_cache")
    # ### end Alembic commands ###
