"""service credential (N10, invariant 11)

The one table in the node that holds somebody else's secret. Two things about it are
deliberate and would be easy to lose in a later edit:

`secret` is a **LargeBinary** holding a Fernet token, never a text column. A text column
invites someone to look at it, and invites a `LIKE` in a debugging session.

The foreign key to `resource` is **ON DELETE CASCADE**. A purged resource (N20) cannot
leave its credential behind, and that is the schema's job rather than the purge job's —
the purge already has a list of things to remember, and "the partner's password" is the
worst possible item to have on it. The node deletes the credential earlier still, when
the resource is withdrawn; this is the backstop, not the mechanism.

Revision ID: 321e3a0701ad
Revises: 49f96a357f4c
Create Date: 2026-10-04 21:21:46.076289

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel renders its own column types (AutoString), so autogenerated
# migrations reference it by name and need it imported.
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "321e3a0701ad"
down_revision: str | Sequence[str] | None = "49f96a357f4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_credential",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("scheme", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("header_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("secret", sa.LargeBinary(), nullable=False),
        sa.Column("set_by_sub", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["resource_id"], ["resource.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    with op.batch_alter_table("service_credential", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_service_credential_tenant_id"), ["tenant_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_service_credential_tenant_id"))

    op.drop_table("service_credential")
    # ### end Alembic commands ###
