"""resource registry (N5)

`resource` is tenant-owned: it carries `tenant_id`, so N4's session filter covers it by
the shape of the model rather than by anyone remembering to add it to a list.

`catalogue_push` is node-global on purpose (R10). It records which tenants have catalogue
changes the Cloud has not been told about; its `tenant_id` is a payload, not an ownership
marker, and filtering it by tenant would break the push it exists to drive.

No unique index on `resource.slug` alone: two organisations naming something `batch-7` is
not a conflict, and making it one would disclose that the other name exists. The
constraint is (tenant_id, slug).

Revision ID: 3778de9637e2
Revises: 73687c4f90a9
Create Date: 2026-09-29 16:57:36.810853

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel renders its own column types (AutoString), so autogenerated
# migrations reference it by name and need it imported.
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3778de9637e2"
down_revision: str | Sequence[str] | None = "73687c4f90a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalogue_push",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("marked_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id"),
    )
    op.create_table(
        "resource",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("kind", sa.Enum("DATASET", "SERVICE", name="resourcekind"), nullable=False),
        sa.Column("shape", sa.Enum("FILE", "BUCKET", "SERVICE", name="shape"), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "WITHDRAWN", name="resourcestatus"), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
        sa.Column(
            "theme",
            sa.Enum(
                "MATERIAL_CHARACTERISATION",
                "PROCESSING",
                "PRODUCT_DEVELOPMENT",
                "VALUE_CHAIN",
                name="theme",
            ),
            nullable=False,
        ),
        sa.Column("licence", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column(
            "discoverability",
            sa.Enum("HIDDEN", "CATALOGUE", "PUBLIC", name="discoverability"),
            nullable=False,
        ),
        sa.Column(
            "visibility",
            sa.Enum("PRIVATE", "ORG", "AGREEMENT", "PUBLIC", name="visibility"),
            nullable=False,
        ),
        sa.Column(
            "classification",
            sa.Enum("SYNTHETIC", "NON_SENSITIVE", "SENSITIVE", name="classification"),
            nullable=False,
        ),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("endpoint_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("openapi_ref", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("invoke_policy", sa.JSON(), nullable=True),
        sa.Column("withdrawn_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("purge_after", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_resource_tenant_slug"),
    )
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_discoverability"), ["discoverability"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_resource_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_resource_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_resource_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_resource_visibility"), ["visibility"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_visibility"))
        batch_op.drop_index(batch_op.f("ix_resource_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_resource_status"))
        batch_op.drop_index(batch_op.f("ix_resource_slug"))
        batch_op.drop_index(batch_op.f("ix_resource_discoverability"))

    op.drop_table("resource")
    op.drop_table("catalogue_push")
    # ### end Alembic commands ###
