"""initial: tenant

Revision ID: 457c943585b3
Revises:
Create Date: 2026-09-26 07:39:29.078576

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "457c943585b3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("group_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenant", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenant_group_path"), ["group_path"], unique=True)
        batch_op.create_index(batch_op.f("ix_tenant_org_id"), ["org_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_tenant_slug"), ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tenant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_slug"))
        batch_op.drop_index(batch_op.f("ix_tenant_org_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_group_path"))

    op.drop_table("tenant")
    # ### end Alembic commands ###
