"""access log (N11, invariant 12)

The table, and the triggers that make "append-only, except one write-once field" a
property of the database rather than of our discipline.

A trigger rather than a grant: the node owns this table, and a table owner bypasses
grants. A trigger does not care who you are, and the node is the only thing with a
connection anyway — so the thing being defended against is our own next bug, or a
statement someone managed to inject through one.

**`bytes` is the single exception, and it is narrow.** Null to a value, once. A transfer's
size is unknown until it has streamed, and the entry has to exist before the stream
starts or a dropped connection would leave no record that access was granted at all. The
trigger permits exactly that write and nothing else: not a second `bytes` write, not any
other column, not a delete.

The SQLite trigger has to name every other column, because SQLite cannot compare rows.
That list going stale when a column is added is the obvious failure, so it is not left to
review: `test_access_log.py` tries to update each column of the live model in turn and
asserts every one is refused, which fails the moment a column is added here and not
there. Postgres compares whole rows and needs no list.

Revision ID: 49f96a357f4c
Revises: 15e0f9bece1b
Create Date: 2026-10-03 11:50:14.479742

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel renders its own column types (AutoString), so autogenerated
# migrations reference it by name and need it imported.
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49f96a357f4c"
down_revision: str | Sequence[str] | None = "15e0f9bece1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_log",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ts", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("subject_sub", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("principal_type", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("actor_azp", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("acting_org", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("decision", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("access_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_access_log_acting_org"), ["acting_org"], unique=False)
        batch_op.create_index(batch_op.f("ix_access_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_access_log_decision"), ["decision"], unique=False)
        batch_op.create_index(batch_op.f("ix_access_log_request_id"), ["request_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_access_log_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_access_log_subject_sub"), ["subject_sub"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_access_log_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_access_log_ts"), ["ts"], unique=False)

    # ### end Alembic commands ###

    _create_append_only_triggers()


#: Everything except `bytes`. Only SQLite needs it; see the module docstring for why it
#: cannot go stale unnoticed.
_IMMUTABLE_COLUMNS = (
    "id",
    "tenant_id",
    "ts",
    "request_id",
    "resource_id",
    "action",
    "subject_sub",
    "principal_type",
    "actor_azp",
    "acting_org",
    "decision",
    "reason",
)

_REFUSAL = "the access log is append-only (N11): only bytes may be set, and only once"


def _create_append_only_triggers() -> None:
    dialect = op.get_bind().dialect.name

    if dialect == "sqlite":
        unchanged = "\n          ".join(
            f"OR NEW.{column} IS NOT OLD.{column}" for column in _IMMUTABLE_COLUMNS
        )
        op.execute(
            f"""
            CREATE TRIGGER access_log_append_only_update
            BEFORE UPDATE ON access_log
            FOR EACH ROW
            WHEN OLD.bytes IS NOT NULL
              OR NEW.bytes IS NULL
              {unchanged}
            BEGIN
                SELECT RAISE(ABORT, '{_REFUSAL}');
            END;
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER access_log_append_only_delete
            BEFORE DELETE ON access_log
            FOR EACH ROW
            BEGIN
                SELECT RAISE(ABORT, '{_REFUSAL}');
            END;
            """
        )
        return

    if dialect == "postgresql":
        # `candidate` is OLD with bytes swapped for the proposed value: if the row still
        # differs after that, something other than bytes was touched. No column list, so
        # nothing to keep in step with the model.
        op.execute(
            f"""
            CREATE FUNCTION access_log_is_append_only() RETURNS trigger AS $$
            DECLARE
                candidate access_log%ROWTYPE;
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION '{_REFUSAL} (DELETE refused)';
                END IF;
                IF OLD.bytes IS NOT NULL OR NEW.bytes IS NULL THEN
                    RAISE EXCEPTION '{_REFUSAL} (bytes already set)';
                END IF;
                candidate := OLD;
                candidate.bytes := NEW.bytes;
                IF ROW(NEW.*) IS DISTINCT FROM ROW(candidate.*) THEN
                    RAISE EXCEPTION '{_REFUSAL} (another column changed)';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            """
            CREATE TRIGGER access_log_append_only
            BEFORE UPDATE OR DELETE ON access_log
            FOR EACH ROW EXECUTE FUNCTION access_log_is_append_only();
            """
        )
        return

    raise RuntimeError(
        f"no append-only trigger for dialect {dialect!r}; the access log must not be "
        "created without one (N11, invariant 12)"
    )


def _drop_append_only_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS access_log_append_only_update")
        op.execute("DROP TRIGGER IF EXISTS access_log_append_only_delete")
    elif dialect == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS access_log_append_only ON access_log")
        op.execute("DROP FUNCTION IF EXISTS access_log_is_append_only()")


def downgrade() -> None:
    """Downgrade schema.

    Triggers first. `batch_alter_table` on SQLite rebuilds the table under a new name and
    copies the rows across — and the delete trigger would refuse the cleanup half of
    that, so dropping an index would fail with an append-only error, which is a memorable
    way to lose an afternoon.
    """
    _drop_append_only_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("access_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_access_log_ts"))
        batch_op.drop_index(batch_op.f("ix_access_log_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_access_log_subject_sub"))
        batch_op.drop_index(batch_op.f("ix_access_log_resource_id"))
        batch_op.drop_index(batch_op.f("ix_access_log_request_id"))
        batch_op.drop_index(batch_op.f("ix_access_log_decision"))
        batch_op.drop_index(batch_op.f("ix_access_log_action"))
        batch_op.drop_index(batch_op.f("ix_access_log_acting_org"))

    op.drop_table("access_log")
    # ### end Alembic commands ###
