"""node identity

Revision ID: 73687c4f90a9
Revises: 457c943585b3
Create Date: 2026-09-28 11:43:45.570885

"""

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel renders its own column types (AutoString), so autogenerated
# migrations reference it by name and need it imported.
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73687c4f90a9"
down_revision: str | Sequence[str] | None = "457c943585b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nodeidentity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("certificate_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nodeidentity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nodeidentity_node_id"), ["node_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nodeidentity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_nodeidentity_node_id"))

    op.drop_table("nodeidentity")
    # ### end Alembic commands ###
